- hosts: all
  become: yes
  become_user: root
  vars:
    mk8s_user_username: "captain"
    mk8s_user_password: ~

    mk8s_user_initial_group: "microk8s"
    mk8s_user_shell: "/bin/bash"
    mk8s_kubectl_alias_key: "kubectl"
    mk8s_kubectl_alias_value: "microk8s.kubectl"
    mk8s_helm_alias_key: "helm"
    mk8s_helm_alias_value: "microk8s.helm"
    mk8s_cluster_inviter: "microk8s-node1"
  roles:
    - microk8s
- post_tasks:
  - name: "Create cluster invitation"
    shell:
      cmd: "microk8s add-node"
    register: "{{ cluster_invite_result }}"
    delegate_to: "{{ mk8s_cluster_inviter }}"
  - name: "Join other nodes cluster"
    shell:
      cmd: "microk8s join {{ cluster_invite_result.stdout }}"
    when: inventory_hostname != mk8s_cluster_inviter
